version: "3"

services:
  juice_shop_app:
    image: bkimminich/juice-shop
    ports:
      - 3000:3000
  puppeteer:
    image: ghcr.io/puppeteer/puppeteer:latest
    command: sh -c "yarn && node node_modules/puppeteer/install.js && yarn test"
    volumes:
      - ./:/home/pptruser
    environment:
      - docker_running=true
    cap_add:
      - SYS_ADMIN
    user: root
