name: Launch tests on chrome
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-chrome:
    runs-on: ubuntu-latest
    services:
      juice_shop_app:
        image: bkimminich/juice-shop
        ports:
          - 3000:3000
    steps:
      - uses: actions/checkout@v3
      - name: Test app
        run: yarn && node node_modules/puppeteer/install.js && yarn test
